### PR TITLE
[2.1inch QTEye] Adafruit 2.1" 480x480 round RGB-666 display

### PR DESCRIPTION
**Pull request by lboue**
2.1inch QTEye example for Adafruit 2.1" 480x480 round RGB-666 display

### CODE REVIEW

**Comment by DJDevon3** [comment]
Doubt I'll be able to merge this one since there are so many changed library files from 9 months ago. This is my personal repo and I do allow commits but I'm also not interested in going far out of my way to review a lot of library/module changes.  Can you tell me which version of Circuit Python you're using so I can validate the library files?

**Comment by lboue** [comment]
Hello,

I am using CircuitPython 9.1.1, the last version and it works.

Regards

**Comment by DJDevon3** [comment]
Ah I see what happened.  The original commit here was using .py library files because the Qualia was still in beta.  I'm updating it to use the 9.1.1 MPY library.  Did you have to resize the images for the 2.1 inch?  The images for the 4" are designed for a 720x720 display.

I don't own the 2.1" display so I'll just trust that your code works for it and will make a commit for it.

**Review by DJDevon3 — APPROVED** [review]
Thank you for the example!  After merging I'll update the library to use the MPY version.

**Comment by lboue** [comment]
> Did you have to resize the images for the 2.1 inch? The images for the 4" are designed for a 720x720 display.

Yes, I had to reduce the image size to 480x480 pixels.

**Pull request merged**
