### PR TITLE
Update code.py

### PR DESCRIPTION
**Pull request by chadleylyell**
You don't have to use a new line every time you want to import a library. Not sure if you know that.

### CODE REVIEW

**Review by DJDevon3 — COMMENTED** [review]
Yes I'm aware you can put them all in-line. That's not the convention for circuit python.  Black & Pylint would have a shit fit if I started doing that and would automatically reformat it back to one line each.  It's also more beginner friendly which I much prefer for sharing examples.

**Comment by chadleylyell** [comment]
Ah, okay! What would make them have a shit fit? What's their reasoning? Just curious, wisdom goes a long way.

**Comment by chadleylyell** [comment]
Ah, okay! Gotcha.

**Comment by DJDevon3** [comment]
I absolutely appreciate your attempt to help optimize & minify the code though.  That was very nice of you.  You're the first person to ever create a pull request on any of my code.  All hail @chadleylyell for being first.

**Pull request closed without merging**
